version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ikv4J.Q!rymgVWfHkfD!FHUY
      POSTGRES_DB: RiverBooks
    ports:
      - "5432:5432"
  cache:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  papercut:
    image: jijiechen/papercut
    restart: always
    ports:
      - "25:25"
      - "37408:37408"
  mongo_email:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
