@RiverBooks.Web_HostAddress = https://localhost:7100

GET {{RiverBooks.Web_HostAddress}}/books/
Accept: application/json

### List Books
GET {{RiverBooks.Web_HostAddress}}/books/
Accept: application/json
