@RiverBooks.Web_HostAddress = https://localhost:7100

### Create User
POST {{RiverBooks.Web_HostAddress}}/users
Accept: application/json
Content-Type: application/json

{
  "email": "bendikj+108@gmail.com",
  "password": "$eCr3t"
}

### Login
POST {{RiverBooks.Web_HostAddress}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "bendikj@gmail.com",
  "password": "$eCr3t"
}

> {% client.global.set("Token", response.body.token); %}

### List Books
GET {{RiverBooks.Web_HostAddress}}/books
Accept: application/json
Authorization: Bearer {{ Token }}

### Get Book
@BookId=418B2BB4-CE5D-4EAA-9B7A-82FA382291DA
GET {{RiverBooks.Web_HostAddress}}/books/{{BookId}}
Accept: application/json

### Create Book
POST {{RiverBooks.Web_HostAddress}}/books
Accept: application/json
Content-Type: application/json

{
  "id": "418B2BB4-CE5D-4EAA-9B7A-82FA382291DA",
  "title": "Modular Monoliths - Getting Started",
  "author": "Steve Smith",
  "price": 29.99
}

#### Get created book
GET {{RiverBooks.Web_HostAddress}}/books/518b2bb4-ce5d-4eaa-9b7a-82fa382291da
Accept: application/json

#### Delete created book
DELETE {{RiverBooks.Web_HostAddress}}/books/518b2bb4-ce5d-4eaa-9b7a-82fa382291da
Accept: application/json

### Update book price
POST {{RiverBooks.Web_HostAddress}}/books/518b2bb4-ce5d-4eaa-9b7a-82fa382291da/pricehistory
Accept: application/json
Content-Type: application/json

{
  "newPrice": -9.99
}

### Add Item to cart
POST {{RiverBooks.Web_HostAddress}}/cart
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "bookId": "{{BookId}}",
  "quantity": 0
}

### List cart
GET {{RiverBooks.Web_HostAddress}}/cart
Accept: application/json
Authorization: Bearer {{Token}}

### List orders
GET {{RiverBooks.Web_HostAddress}}/orders
Accept: application/json
Authorization: Bearer {{Token}}

### Checkout Cart
POST {{RiverBooks.Web_HostAddress}}/cart/checkout
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "shippingAddressId": "2b8f24c0-a3cc-41c7-8cda-431b24483491",
  "billingAddressId": "2b8f24c0-a3cc-41c7-8cda-431b24483491"
}

### List addresses
GET {{RiverBooks.Web_HostAddress}}/user/address
Accept: application/json
Authorization: Bearer {{Token}}

### Add address
POST {{RiverBooks.Web_HostAddress}}/user/address
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "Street1": "2124 Main",
  "Street2": "",
  "City": "Kent",
  "State": "OH",
  "PostalCode": "44444",
  "Country": "USA"
}

### Flush cache
POST {{RiverBooks.Web_HostAddress}}/user/address
Accept: application/json
Content-Type: application/json

{}
